# Generated by Django 3.2.12 on 2022-02-16 08:33

from django.db import migrations
import django.forms.widgets
import page.blocks.custom_choice_block
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_alter_defaultpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultpage',
            name='body',
            field=wagtail.core.fields.StreamField([('three_column_image_link_block', wagtail.core.blocks.StructBlock([('block_id', wagtail.core.blocks.CharBlock(required=False)), ('block_header', wagtail.core.blocks.CharBlock()), ('button_link', wagtail.core.blocks.StructBlock([('link_type', page.blocks.custom_choice_block.CustomChoiceBlock(choices=(('', 'None'), ('url', 'URL'), ('page', 'Page'), ('document', 'Document'), ('email', 'Email'), ('anchor', 'Anchor'), ('phone', 'Phone')), default='', label='Type', required=False, widget=django.forms.widgets.RadioSelect)), ('link_opens_in_new_tab', wagtail.core.blocks.BooleanBlock(required=False)), ('url', wagtail.core.blocks.CharBlock(label='URL', required=False)), ('page', wagtail.core.blocks.PageChooserBlock(required=False)), ('document', wagtail.documents.blocks.DocumentChooserBlock(required=False)), ('email', wagtail.core.blocks.EmailBlock(required=False)), ('phone', wagtail.core.blocks.CharBlock(required=False)), ('anchor', wagtail.core.blocks.CharBlock(help_text='This will only work properly if there is an anchor block dropped on the home page', required=False)), ('link_text', wagtail.core.blocks.CharBlock(label='Text', required=False))])), ('image_links', wagtail.core.blocks.StreamBlock([('image_link_block', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('block_title', wagtail.core.blocks.CharBlock()), ('link', wagtail.core.blocks.StructBlock([('link_type', page.blocks.custom_choice_block.CustomChoiceBlock(choices=(('url', 'URL'), ('page', 'Page'), ('document', 'Document'), ('email', 'Email'), ('anchor', 'Anchor'), ('phone', 'Phone')), default='url', label='Type', required=False, widget=django.forms.widgets.RadioSelect)), ('link_opens_in_new_tab', wagtail.core.blocks.BooleanBlock(required=False)), ('url', wagtail.core.blocks.CharBlock(label='URL', required=False)), ('page', wagtail.core.blocks.PageChooserBlock(required=False)), ('document', wagtail.documents.blocks.DocumentChooserBlock(required=False)), ('email', wagtail.core.blocks.EmailBlock(required=False)), ('phone', wagtail.core.blocks.CharBlock(required=False)), ('anchor', wagtail.core.blocks.CharBlock(help_text='This will only work properly if there is an anchor block dropped on the home page', required=False)), ('link_text', wagtail.core.blocks.CharBlock(label='Text', required=False))]))]))]))])), ('square_image_text_block', wagtail.core.blocks.StructBlock([('block_id', wagtail.core.blocks.CharBlock(required=False)), ('images', wagtail.core.blocks.StreamBlock([('image', wagtail.images.blocks.ImageChooserBlock())])), ('text_column', wagtail.core.blocks.StructBlock([('text_header', wagtail.core.blocks.CharBlock()), ('text_content', wagtail.core.blocks.RichTextBlock()), ('button_link', wagtail.core.blocks.StructBlock([('link_type', page.blocks.custom_choice_block.CustomChoiceBlock(choices=(('', 'None'), ('url', 'URL'), ('page', 'Page'), ('document', 'Document'), ('email', 'Email'), ('anchor', 'Anchor'), ('phone', 'Phone')), default='', label='Type', required=False, widget=django.forms.widgets.RadioSelect)), ('link_opens_in_new_tab', wagtail.core.blocks.BooleanBlock(required=False)), ('url', wagtail.core.blocks.CharBlock(label='URL', required=False)), ('page', wagtail.core.blocks.PageChooserBlock(required=False)), ('document', wagtail.documents.blocks.DocumentChooserBlock(required=False)), ('email', wagtail.core.blocks.EmailBlock(required=False)), ('phone', wagtail.core.blocks.CharBlock(required=False)), ('anchor', wagtail.core.blocks.CharBlock(help_text='This will only work properly if there is an anchor block dropped on the home page', required=False)), ('link_text', wagtail.core.blocks.CharBlock(label='Text', required=False))]))]))]))], blank=True, null=True),
        ),
    ]
