# Generated by Django 3.2.12 on 2022-02-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_auto_20220221_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(choices=[('main-header-menu', 'Main Header Menu'), ('careers-header-menu', 'Careers Header Menu')], max_length=30),
        ),
    ]
