# Generated by Django 3.2.12 on 2022-02-23 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_auto_20220223_2155'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormSettings',
        ),
    ]
