# Generated by Django 3.2.12 on 2022-03-01 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('page', '0017_alter_defaultpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerfooter',
            name='privacy_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='page.defaultpage'),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='terms_of_service_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='page.defaultpage'),
        ),
        migrations.CreateModel(
            name='GTMSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtm_header_code', models.CharField(blank=True, default='', help_text='The code that goes high as possible in the <head> tag', max_length=250, null=True, verbose_name='GTM Header Code')),
                ('gtm_body_code', models.CharField(blank=True, default='', help_text='The code that goes right after opening the <body> tag', max_length=250, null=True, verbose_name='GTM Body Code')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'GTM Settings',
            },
        ),
    ]
