# Generated by Django 3.2.12 on 2022-03-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0018_auto_20220301_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headerfooter',
            name='privacy_page',
        ),
        migrations.RemoveField(
            model_name='headerfooter',
            name='terms_of_service_page',
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(choices=[('main-header-menu', 'Main Header Menu'), ('careers-header-menu', 'Careers Header Menu'), ('footer-under-copyright-menu', 'Footer Under Copyright Menu')], max_length=30),
        ),
    ]
