# Generated by Django 3.2.12 on 2022-03-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0019_auto_20220301_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gtmsettings',
            name='gtm_body_code',
            field=models.CharField(blank=True, default='', help_text='The code that goes right after opening the <body> tag', max_length=1024, null=True, verbose_name='GTM Body Code'),
        ),
        migrations.AlterField(
            model_name='gtmsettings',
            name='gtm_header_code',
            field=models.CharField(blank=True, default='', help_text='The code that goes high as possible in the <head> tag', max_length=1024, null=True, verbose_name='GTM Header Code'),
        ),
    ]
