# Generated by Django 3.2.12 on 2022-05-23 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediamodels', '0002_auto_20210809_0949'),
        ('page', '0022_alter_defaultpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultpage',
            name='og_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_og_image', to='mediamodels.customimage', verbose_name='OG:Image'),
        ),
    ]
