# Generated by Django 3.2.12 on 2022-06-09 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('page', '0025_auto_20220531_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerfooter',
            name='footer_contact_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.page'),
        ),
    ]
