# Generated by Django 3.2.12 on 2022-06-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0026_headerfooter_footer_contact_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerfooter',
            name='footer_form_text',
            field=models.CharField(blank=True, default='', help_text='The text that shows above the footer contact button.', max_length=512, null=True, verbose_name='Footer contact text'),
        ),
    ]
