# Generated by Django 3.2.12 on 2022-06-13 14:28

from django.db import migrations
import django.forms.widgets
import page.blocks.custom_choice_block
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0027_headerfooter_footer_form_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='menu_link',
            field=wagtail.core.fields.StreamField([('link_block', wagtail.core.blocks.StructBlock([('link_type', page.blocks.custom_choice_block.CustomChoiceBlock(choices=(('', 'None'), ('url', 'URL'), ('page', 'Page'), ('document', 'Document'), ('anchor', 'Anchor')), default='', label='Type', required=False, widget=django.forms.widgets.RadioSelect)), ('link_opens_in_new_tab', wagtail.core.blocks.BooleanBlock(required=False)), ('url', wagtail.core.blocks.CharBlock(label='URL', required=False)), ('page', wagtail.core.blocks.PageChooserBlock(required=False)), ('document', wagtail.documents.blocks.DocumentChooserBlock(required=False)), ('anchor', wagtail.core.blocks.CharBlock(help_text='This will only work properly if there is an anchor block dropped on the home page', required=False)), ('link_text', wagtail.core.blocks.CharBlock(label='Text', required=False))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='sub_menu',
            field=wagtail.core.fields.StreamField([('submenu_block', wagtail.core.blocks.StructBlock([('link_type', page.blocks.custom_choice_block.CustomChoiceBlock(choices=(('', 'None'), ('url', 'URL'), ('page', 'Page'), ('document', 'Document'), ('anchor', 'Anchor')), default='', label='Type', required=False, widget=django.forms.widgets.RadioSelect)), ('link_opens_in_new_tab', wagtail.core.blocks.BooleanBlock(required=False)), ('url', wagtail.core.blocks.CharBlock(label='URL', required=False)), ('page', wagtail.core.blocks.PageChooserBlock(required=False)), ('document', wagtail.documents.blocks.DocumentChooserBlock(required=False)), ('anchor', wagtail.core.blocks.CharBlock(help_text='This will only work properly if there is an anchor block dropped on the home page', required=False)), ('link_text', wagtail.core.blocks.CharBlock(label='Text', required=False))]))], blank=True, null=True),
        ),
    ]
