# Generated by Django 3.2.16 on 2022-11-25 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediamodels', '0002_auto_20210809_0949'),
        ('page', '0034_auto_20221125_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignpage',
            name='connect_with_us_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mediamodels.customimage'),
        ),
        migrations.AddField(
            model_name='campaignpage',
            name='fairhill_experience_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mediamodels.customimage'),
        ),
        migrations.AddField(
            model_name='campaignpage',
            name='fairhill_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mediamodels.customimage'),
        ),
        migrations.AddField(
            model_name='campaignpage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mediamodels.customimage'),
        ),
        migrations.AddField(
            model_name='campaignpage',
            name='image_row_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mediamodels.customimage'),
        ),
        migrations.AddField(
            model_name='campaignpage',
            name='image_row_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mediamodels.customimage'),
        ),
        migrations.AddField(
            model_name='campaignpage',
            name='image_row_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mediamodels.customimage'),
        ),
        migrations.AddField(
            model_name='campaignpage',
            name='who_we_serve_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mediamodels.customimage'),
        ),
    ]
