# Generated by Django 3.2.16 on 2023-01-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0040_alter_defaultpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerfooter',
            name='footer_address_1',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='headerfooter',
            name='footer_address_2',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(choices=[('main-header-menu', 'Main Header Menu'), ('careers-header-menu', 'Workers Header Menu'), ('footer-extra-menu', 'Footer Extra Menu')], max_length=30),
        ),
    ]
