# Generated by Django 3.2.19 on 2023-07-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0044_alter_defaultpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerfooter',
            name='footer_address_3',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
    ]
