# Generated by Django 3.2.19 on 2023-07-18 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediamodels', '0002_auto_20210809_0949'),
        ('page', '0060_alter_social_socials'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerfooter',
            name='footer_background',
            field=models.ForeignKey(blank=True, help_text='Background design for the footer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='footer_background', to='mediamodels.customimage'),
        ),
    ]
