# Generated by Django 3.2.19 on 2023-07-31 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0071_alter_defaultpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerfooter',
            name='footer_contact_form',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Footer HS Form'),
        ),
    ]
