# Generated by Django 3.2.6 on 2021-08-09 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediamodels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customimage',
            name='image_2x',
        ),
        migrations.RemoveField(
            model_name='customimage',
            name='image_3x',
        ),
    ]
